spring:
  application:
    name: first-boot
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
logging:
  file:
    path: ./log/first-bootlog.log
  level:
    root: info
debug: true
---
spring:
  application:
    name: first-boot
  profiles: dev
server:
  port: 8899
  tomcat:
    uri-encoding: UTF-8
logging:
  file:
    path: ./log/first-bootlog.log
  level:
    root: error
